#!/bin/bash

# This program is used to start and stop multiple nodes
# Usage: bash node_runner <num nodes> <base port> <test duration>

# Variables
NUM_NODES=${1:-5}       # Number of nodes to create
BASE_PORT=${2:-8100}    # Base port to start creating nodes
TEST_DURATION=${3:-10}  # Seconds

echo Starting Nodes...

# start python script for each node
for ((i=1; i<=$NUM_NODES; i++))
do
  python main.py $((BASE_PORT+i)) $((i)) &
  sleep .2
done

echo Nodes Started

# if test duration is not negative
if [ $TEST_DURATION -gt 0 ]
then
# run test for X seconds
sleep $TEST_DURATION

# then stop all nodes
echo Killing Nodes...
pkill -f main.py
echo Nodes Killed

fi



# check by using: "ps -fA | grep python"