#!/bin/bash

# This program is used to start and stop multiple nodes
# Usage: bash node_runner <num nodes> <base port> <test duration>

# Variables
NUM_NODES=${1:-5}       # Number of nodes to create
BASE_PORT=${2:-8080}    # Base port to start creating nodes
TEST_DURATION=${3:-10}  # Seconds

echo Starting Nodes...

# start python script for each node
for ((i=0; i<$NUM_NODES; i++))
do
  python main.py $((BASE_PORT+i)) &
  sleep .1
done

echo Nodes Started

sleep $TEST_DURATION

# stop all nodes
echo Killing Nodes...
pkill -f main.py
echo Nodes Killed

# check by using: "ps -fA | grep python"